---
 - hosts: localhost
   tasks:
    - name: Creating a Security Group
      ec2_group:
        name: aws_ansible
        description: from ansible
        vpc_id: "{{ vpc }}"
        region: "{{ region }}"
        rules:
         - proto: tcp
           from_port: 22
           to_port: 22
           cidr_ip: 0.0.0.0/0
         - proto: tcp
           from_port: 80
           to_port: 80
           cidr_ip: 0.0.0.0/0
